# Build directory for MN_RU experiments
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/MN_RU)

# MN_RU executables
add_executable(MN_RBC_random random.cpp)
add_executable(MN_RU_full_coverage full_coverage.cpp)
add_executable(MN_RU_new_data new_data.cpp)
add_executable(MN_RU_unreachable_points_sampl_reachable unreachable_points_sampl_reachable.cpp)

set_target_properties(MN_RU_random PROPERTIES OUTPUT_NAME random)
set_target_properties(MN_RU_full_coverage PROPERTIES OUTPUT_NAME full_coverage)
set_target_properties(MN_RU_new_data PROPERTIES OUTPUT_NAME new_data)
set_target_properties(MN_RU_unreachable_points_sampl_reachable PROPERTIES OUTPUT_NAME unreachable_points_sampl_reachable)

# Link libraries
target_link_libraries(MN_RU_random hnswlib_utils usearch_utils duckdb)
target_link_libraries(MN_RU_full_coverage hnswlib_utils usearch_utils duckdb)
target_link_libraries(MN_RU_new_data hnswlib_utils usearch_utils duckdb)
target_link_libraries(MN_RU_unreachable_points_sampl_reachable hnswlib_utils usearch_utils duckdb)